apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task-manager-web
  template:
    metadata:
      labels:
        app: task-manager-web
    spec:
      containers:
      - name: task-manager-web
        image: 2019mmjitu/task-manager-web:latest
        ports:
        - containerPort: 80
